# Generated by Django 3.2.25 on 2024-05-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='enquiry_type',
            field=models.CharField(choices=[('DESIGN_CONSULTATION', 'Design Consultation Enquiry'), ('PRODUCT_QUERY', 'Product Query'), ('ORDER_QUERY', 'Order Query'), ('OTHER', 'Other')], default='DS', max_length=254),
        ),
    ]
